#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using CapaDominio;

namespace CapaDominio	
{
	public partial class Actuacion
	{
		private int idActuacion;
		public virtual int IdActuacion
		{
			get
			{
				return this.idActuacion;
			}
			set
			{
				this.idActuacion = value;
			}
		}
		
		private int idProyecto;
		public virtual int IdProyecto
		{
			get
			{
				return this.idProyecto;
			}
			set
			{
				this.idProyecto = value;
			}
		}
		
		private DateTime? fecha;
		public virtual DateTime? Fecha
		{
			get
			{
				return this.fecha;
			}
			set
			{
				this.fecha = value;
			}
		}
		
		private string detalle;
		public virtual string Detalle
		{
			get
			{
				return this.detalle;
			}
			set
			{
				this.detalle = value;
			}
		}
		
		private int? idOrganismo;
		public virtual int? IdOrganismo
		{
			get
			{
				return this.idOrganismo;
			}
			set
			{
				this.idOrganismo = value;
			}
		}
		
		private int? idViaComunicacion;
		public virtual int? IdViaComunicacion
		{
			get
			{
				return this.idViaComunicacion;
			}
			set
			{
				this.idViaComunicacion = value;
			}
		}
		
		private int? idPersona;
		public virtual int? IdPersona
		{
			get
			{
				return this.idPersona;
			}
			set
			{
				this.idPersona = value;
			}
		}
		
		private Organismo organismo;
		public virtual Organismo Organismo
		{
			get
			{
				return this.organismo;
			}
			set
			{
				this.organismo = value;
			}
		}
		
		private Proyecto proyecto;
		public virtual Proyecto Proyecto
		{
			get
			{
				return this.proyecto;
			}
			set
			{
				this.proyecto = value;
			}
		}
		
		private ViaComunicacion viaComunicacion;
		public virtual ViaComunicacion ViaComunicacion
		{
			get
			{
				return this.viaComunicacion;
			}
			set
			{
				this.viaComunicacion = value;
			}
		}
		
		private Persona persona;
		public virtual Persona Persona
		{
			get
			{
				return this.persona;
			}
			set
			{
				this.persona = value;
			}
		}
		
	}
}
#pragma warning restore 1591
