#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using CapaDominio;

namespace CapaDominio	
{
	public partial class Desembolso
	{
		private int idDesembolso;
		public virtual int IdDesembolso
		{
			get
			{
				return this.idDesembolso;
			}
			set
			{
				this.idDesembolso = value;
			}
		}
		
		private string nombre;
		public virtual string Nombre
		{
			get
			{
				return this.nombre;
			}
			set
			{
				this.nombre = value;
			}
		}
		
		private DateTime fechaDesembolso;
		public virtual DateTime FechaDesembolso
		{
			get
			{
				return this.fechaDesembolso;
			}
			set
			{
				this.fechaDesembolso = value;
			}
		}
		
		private decimal montoDesembolso;
		public virtual decimal MontoDesembolso
		{
			get
			{
				return this.montoDesembolso;
			}
			set
			{
				this.montoDesembolso = value;
			}
		}
		
		private int idProyecto;
		public virtual int IdProyecto
		{
			get
			{
				return this.idProyecto;
			}
			set
			{
				this.idProyecto = value;
			}
		}
		
		private int idEtapa;
		public virtual int IdEtapa
		{
			get
			{
				return this.idEtapa;
			}
			set
			{
				this.idEtapa = value;
			}
		}
		
		private Etapa etapa;
		public virtual Etapa Etapa
		{
			get
			{
				return this.etapa;
			}
			set
			{
				this.etapa = value;
			}
		}
		
		private Proyecto proyecto;
		public virtual Proyecto Proyecto
		{
			get
			{
				return this.proyecto;
			}
			set
			{
				this.proyecto = value;
			}
		}
		
	}
}
#pragma warning restore 1591
