#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using CapaDominio;

namespace CapaDominio	
{
	public partial class Etapa
	{
		private int idEtapa;
		public virtual int IdEtapa
		{
			get
			{
				return this.idEtapa;
			}
			set
			{
				this.idEtapa = value;
			}
		}
		
		private int idProyecto;
		public virtual int IdProyecto
		{
			get
			{
				return this.idProyecto;
			}
			set
			{
				this.idProyecto = value;
			}
		}
		
		private string nombre;
		public virtual string Nombre
		{
			get
			{
				return this.nombre;
			}
			set
			{
				this.nombre = value;
			}
		}
		
		private DateTime? fechaInicio;
		public virtual DateTime? FechaInicio
		{
			get
			{
				return this.fechaInicio;
			}
			set
			{
				this.fechaInicio = value;
			}
		}
		
		private DateTime? fechaFin;
		public virtual DateTime? FechaFin
		{
			get
			{
				return this.fechaFin;
			}
			set
			{
				this.fechaFin = value;
			}
		}
		
		private int? idTipoEstadoEtapa;
		public virtual int? IdTipoEstadoEtapa
		{
			get
			{
				return this.idTipoEstadoEtapa;
			}
			set
			{
				this.idTipoEstadoEtapa = value;
			}
		}
		
		private bool? rendicion;
		public virtual bool? Rendicion
		{
			get
			{
				return this.rendicion;
			}
			set
			{
				this.rendicion = value;
			}
		}
		
		private bool? informe;
		public virtual bool? Informe
		{
			get
			{
				return this.informe;
			}
			set
			{
				this.informe = value;
			}
		}
		
		private Proyecto proyecto;
		public virtual Proyecto Proyecto
		{
			get
			{
				return this.proyecto;
			}
			set
			{
				this.proyecto = value;
			}
		}
		
		private TipoEstadoEtapa tipoEstadoEtapa;
		public virtual TipoEstadoEtapa TipoEstadoEtapa
		{
			get
			{
				return this.tipoEstadoEtapa;
			}
			set
			{
				this.tipoEstadoEtapa = value;
			}
		}
		
		private IList<Desembolso> desembolsos = new List<Desembolso>();
		public virtual IList<Desembolso> Desembolsos
		{
			get
			{
				return this.desembolsos;
			}
		}
		
		private IList<Actividad> actividads = new List<Actividad>();
		public virtual IList<Actividad> Actividads
		{
			get
			{
				return this.actividads;
			}
		}
		
	}
}
#pragma warning restore 1591
