#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using CapaDominio;

namespace CapaDominio	
{
	public partial class Localidad
	{
		private int idLocalidad;
		public virtual int IdLocalidad
		{
			get
			{
				return this.idLocalidad;
			}
			set
			{
				this.idLocalidad = value;
			}
		}
		
		private string nombre;
		public virtual string Nombre
		{
			get
			{
				return this.nombre;
			}
			set
			{
				this.nombre = value;
			}
		}
		
		private string codigoPostal;
		public virtual string CodigoPostal
		{
			get
			{
				return this.codigoPostal;
			}
			set
			{
				this.codigoPostal = value;
			}
		}
		
		private IList<Proyecto> proyectos = new List<Proyecto>();
		public virtual IList<Proyecto> Proyectos
		{
			get
			{
				return this.proyectos;
			}
		}
		
		private IList<Empresa> empresas = new List<Empresa>();
		public virtual IList<Empresa> Empresas
		{
			get
			{
				return this.empresas;
			}
		}
		
		private IList<Organismo> organismos = new List<Organismo>();
		public virtual IList<Organismo> Organismos
		{
			get
			{
				return this.organismos;
			}
		}
		
		private IList<UdtUvt> udtUvts = new List<UdtUvt>();
		public virtual IList<UdtUvt> UdtUvts
		{
			get
			{
				return this.udtUvts;
			}
		}
		
	}
}
#pragma warning restore 1591
