#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace CapaDominio	
{
	public partial class pr02ResultSet0
	{
		private int _idProyecto;
		public virtual int idProyecto
		{
			get
			{
				return this._idProyecto;
			}
			set
			{
				this._idProyecto = value;
			}
		}
		
		private int _idConvocatoria;
		public virtual int idConvocatoria
		{
			get
			{
				return this._idConvocatoria;
			}
			set
			{
				this._idConvocatoria = value;
			}
		}
		
		private string _nombre;
		public virtual string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				this._nombre = value;
			}
		}
		
		private string _numeroExpediente;
		public virtual string numeroExpediente
		{
			get
			{
				return this._numeroExpediente;
			}
			set
			{
				this._numeroExpediente = value;
			}
		}
		
		private decimal? _montoSolicitado;
		public virtual decimal? montoSolicitado
		{
			get
			{
				return this._montoSolicitado;
			}
			set
			{
				this._montoSolicitado = value;
			}
		}
		
		private decimal? _montoContraparte;
		public virtual decimal? montoContraparte
		{
			get
			{
				return this._montoContraparte;
			}
			set
			{
				this._montoContraparte = value;
			}
		}
		
		private decimal? _montoTotal;
		public virtual decimal? montoTotal
		{
			get
			{
				return this._montoTotal;
			}
			set
			{
				this._montoTotal = value;
			}
		}
		
		private int? _idPersona;
		public virtual int? idPersona
		{
			get
			{
				return this._idPersona;
			}
			set
			{
				this._idPersona = value;
			}
		}
		
		private int? _idEmpresa;
		public virtual int? idEmpresa
		{
			get
			{
				return this._idEmpresa;
			}
			set
			{
				this._idEmpresa = value;
			}
		}
		
		private string _localidad;
		public virtual string localidad
		{
			get
			{
				return this._localidad;
			}
			set
			{
				this._localidad = value;
			}
		}
		
		private string _tipoProyecto;
		public virtual string tipoProyecto
		{
			get
			{
				return this._tipoProyecto;
			}
			set
			{
				this._tipoProyecto = value;
			}
		}
		
		private string _tipoEstado;
		public virtual string tipoEstado
		{
			get
			{
				return this._tipoEstado;
			}
			set
			{
				this._tipoEstado = value;
			}
		}
		
		private int? _anio;
		public virtual int? anio
		{
			get
			{
				return this._anio;
			}
			set
			{
				this._anio = value;
			}
		}
		
	}
}
#pragma warning restore 1591
