#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using CapaDominio;

namespace CapaDominio	
{
	public partial class Proyecto
	{
		private int idProyecto;
		public virtual int IdProyecto
		{
			get
			{
				return this.idProyecto;
			}
			set
			{
				this.idProyecto = value;
			}
		}
		
		private int idConvocatoria;
		public virtual int IdConvocatoria
		{
			get
			{
				return this.idConvocatoria;
			}
			set
			{
				this.idConvocatoria = value;
			}
		}
		
		private string nombre;
		public virtual string Nombre
		{
			get
			{
				return this.nombre;
			}
			set
			{
				this.nombre = value;
			}
		}
		
		private string numeroExpediente;
		public virtual string NumeroExpediente
		{
			get
			{
				return this.numeroExpediente;
			}
			set
			{
				this.numeroExpediente = value;
			}
		}
		
		private decimal? montoSolicitado;
		public virtual decimal? MontoSolicitado
		{
			get
			{
				return this.montoSolicitado;
			}
			set
			{
				this.montoSolicitado = value;
			}
		}
		
		private decimal? montoContraparte;
		public virtual decimal? MontoContraparte
		{
			get
			{
				return this.montoContraparte;
			}
			set
			{
				this.montoContraparte = value;
			}
		}
		
		private decimal? montoTotal;
		public virtual decimal? MontoTotal
		{
			get
			{
				return this.montoTotal;
			}
			set
			{
				this.montoTotal = value;
			}
		}
		
		private int? idPersona;
		public virtual int? IdPersona
		{
			get
			{
				return this.idPersona;
			}
			set
			{
				this.idPersona = value;
			}
		}
		
		private int? idEmpresa;
		public virtual int? IdEmpresa
		{
			get
			{
				return this.idEmpresa;
			}
			set
			{
				this.idEmpresa = value;
			}
		}
		
		private int? idLocalidad;
		public virtual int? IdLocalidad
		{
			get
			{
				return this.idLocalidad;
			}
			set
			{
				this.idLocalidad = value;
			}
		}
		
		private Persona persona;
		public virtual Persona Persona
		{
			get
			{
				return this.persona;
			}
			set
			{
				this.persona = value;
			}
		}
		
		private Localidad localidad;
		public virtual Localidad Localidad
		{
			get
			{
				return this.localidad;
			}
			set
			{
				this.localidad = value;
			}
		}
		
		private Empresa empresa;
		public virtual Empresa Empresa
		{
			get
			{
				return this.empresa;
			}
			set
			{
				this.empresa = value;
			}
		}
		
		private IList<Etapa> etapas = new List<Etapa>();
		public virtual IList<Etapa> Etapas
		{
			get
			{
				return this.etapas;
			}
		}
		
		private IList<Auditorium> auditoria = new List<Auditorium>();
		public virtual IList<Auditorium> Auditoria
		{
			get
			{
				return this.auditoria;
			}
		}
		
		private IList<Actuacion> actuacions = new List<Actuacion>();
		public virtual IList<Actuacion> Actuacions
		{
			get
			{
				return this.actuacions;
			}
		}
		
	}
}
#pragma warning restore 1591
