#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using CapaDominio;

namespace CapaDominio	
{
	public partial class ProyectoCofecyt
	{
		private int idProyectoCofecyt;
		public virtual int IdProyectoCofecyt
		{
			get
			{
				return this.idProyectoCofecyt;
			}
			set
			{
				this.idProyectoCofecyt = value;
			}
		}
		
		private string numeroConvenio;
		public virtual string NumeroConvenio
		{
			get
			{
				return this.numeroConvenio;
			}
			set
			{
				this.numeroConvenio = value;
			}
		}
		
		private string numeroExpedienteDga;
		public virtual string NumeroExpedienteDga
		{
			get
			{
				return this.numeroExpedienteDga;
			}
			set
			{
				this.numeroExpedienteDga = value;
			}
		}
		
		private int? idUdtUvt;
		public virtual int? IdUdtUvt
		{
			get
			{
				return this.idUdtUvt;
			}
			set
			{
				this.idUdtUvt = value;
			}
		}
		
		private int? idDirector;
		public virtual int? IdDirector
		{
			get
			{
				return this.idDirector;
			}
			set
			{
				this.idDirector = value;
			}
		}
		
		private DateTime? fechaPresentacion;
		public virtual DateTime? FechaPresentacion
		{
			get
			{
				return this.fechaPresentacion;
			}
			set
			{
				this.fechaPresentacion = value;
			}
		}
		
		private DateTime? ultimaEvaluacionTecnica;
		public virtual DateTime? UltimaEvaluacionTecnica
		{
			get
			{
				return this.ultimaEvaluacionTecnica;
			}
			set
			{
				this.ultimaEvaluacionTecnica = value;
			}
		}
		
		private DateTime? fechaFinalizacion;
		public virtual DateTime? FechaFinalizacion
		{
			get
			{
				return this.fechaFinalizacion;
			}
			set
			{
				this.fechaFinalizacion = value;
			}
		}
		
		private int? duracionEstimada;
		public virtual int? DuracionEstimada
		{
			get
			{
				return this.duracionEstimada;
			}
			set
			{
				this.duracionEstimada = value;
			}
		}
		
		private int? duracionEstimadaIfaa;
		public virtual int? DuracionEstimadaIfaa
		{
			get
			{
				return this.duracionEstimadaIfaa;
			}
			set
			{
				this.duracionEstimadaIfaa = value;
			}
		}
		
		private string beneficiarios;
		public virtual string Beneficiarios
		{
			get
			{
				return this.beneficiarios;
			}
			set
			{
				this.beneficiarios = value;
			}
		}
		
		private string entidadesIntervinientes;
		public virtual string EntidadesIntervinientes
		{
			get
			{
				return this.entidadesIntervinientes;
			}
			set
			{
				this.entidadesIntervinientes = value;
			}
		}
		
		private int? idTipoEstadoCofecyt;
		public virtual int? IdTipoEstadoCofecyt
		{
			get
			{
				return this.idTipoEstadoCofecyt;
			}
			set
			{
				this.idTipoEstadoCofecyt = value;
			}
		}
		
		private int? idContactoBeneficiario;
		public virtual int? IdContactoBeneficiario
		{
			get
			{
				return this.idContactoBeneficiario;
			}
			set
			{
				this.idContactoBeneficiario = value;
			}
		}
		
		private decimal? montoSolicitadoCofecyt;
		public virtual decimal? MontoSolicitadoCofecyt
		{
			get
			{
				return this.montoSolicitadoCofecyt;
			}
			set
			{
				this.montoSolicitadoCofecyt = value;
			}
		}
		
		private decimal? montoContraparteCofecyt;
		public virtual decimal? MontoContraparteCofecyt
		{
			get
			{
				return this.montoContraparteCofecyt;
			}
			set
			{
				this.montoContraparteCofecyt = value;
			}
		}
		
		private decimal? montoTotalCofecyt;
		public virtual decimal? MontoTotalCofecyt
		{
			get
			{
				return this.montoTotalCofecyt;
			}
			set
			{
				this.montoTotalCofecyt = value;
			}
		}
		
		private decimal? montoTotalDgaCofecyt;
		public virtual decimal? MontoTotalDgaCofecyt
		{
			get
			{
				return this.montoTotalDgaCofecyt;
			}
			set
			{
				this.montoTotalDgaCofecyt = value;
			}
		}
		
		private decimal? montoDevolucionCofecyt;
		public virtual decimal? MontoDevolucionCofecyt
		{
			get
			{
				return this.montoDevolucionCofecyt;
			}
			set
			{
				this.montoDevolucionCofecyt = value;
			}
		}
		
		private decimal? montoRescindidoCofecyt;
		public virtual decimal? MontoRescindidoCofecyt
		{
			get
			{
				return this.montoRescindidoCofecyt;
			}
			set
			{
				this.montoRescindidoCofecyt = value;
			}
		}
		
		private string titulo;
		public virtual string Titulo
		{
			get
			{
				return this.titulo;
			}
			set
			{
				this.titulo = value;
			}
		}
		
		private string observaciones;
		public virtual string Observaciones
		{
			get
			{
				return this.observaciones;
			}
			set
			{
				this.observaciones = value;
			}
		}
		
		private string objetivos;
		public virtual string Objetivos
		{
			get
			{
				return this.objetivos;
			}
			set
			{
				this.objetivos = value;
			}
		}
		
		private string numeroEspedienteCopade;
		public virtual string NumeroEspedienteCopade
		{
			get
			{
				return this.numeroEspedienteCopade;
			}
			set
			{
				this.numeroEspedienteCopade = value;
			}
		}
		
		private int? idTematica;
		public virtual int? IdTematica
		{
			get
			{
				return this.idTematica;
			}
			set
			{
				this.idTematica = value;
			}
		}
		
		private int? idSector;
		public virtual int? IdSector
		{
			get
			{
				return this.idSector;
			}
			set
			{
				this.idSector = value;
			}
		}
		
		private int? idLocalidad;
		public virtual int? IdLocalidad
		{
			get
			{
				return this.idLocalidad;
			}
			set
			{
				this.idLocalidad = value;
			}
		}
		
		private int idConvocatoria;
		public virtual int IdConvocatoria
		{
			get
			{
				return this.idConvocatoria;
			}
			set
			{
				this.idConvocatoria = value;
			}
		}
		
		private string destinatarios;
		public virtual string Destinatarios
		{
			get
			{
				return this.destinatarios;
			}
			set
			{
				this.destinatarios = value;
			}
		}
		
		private string descripcion;
		public virtual string Descripcion
		{
			get
			{
				return this.descripcion;
			}
			set
			{
				this.descripcion = value;
			}
		}
		
		private UdtUvt udtUvt;
		public virtual UdtUvt UdtUvt
		{
			get
			{
				return this.udtUvt;
			}
			set
			{
				this.udtUvt = value;
			}
		}
		
		private TipoEstadoCofecyt tipoEstadoCofecyt;
		public virtual TipoEstadoCofecyt TipoEstadoCofecyt
		{
			get
			{
				return this.tipoEstadoCofecyt;
			}
			set
			{
				this.tipoEstadoCofecyt = value;
			}
		}
		
		private Persona persona;
		public virtual Persona Persona
		{
			get
			{
				return this.persona;
			}
			set
			{
				this.persona = value;
			}
		}
		
		private Persona persona1;
		public virtual Persona Persona1
		{
			get
			{
				return this.persona1;
			}
			set
			{
				this.persona1 = value;
			}
		}
		
		private Tematica tematica;
		public virtual Tematica Tematica
		{
			get
			{
				return this.tematica;
			}
			set
			{
				this.tematica = value;
			}
		}
		
		private Sector sector;
		public virtual Sector Sector
		{
			get
			{
				return this.sector;
			}
			set
			{
				this.sector = value;
			}
		}
		
		private Localidad localidad;
		public virtual Localidad Localidad
		{
			get
			{
				return this.localidad;
			}
			set
			{
				this.localidad = value;
			}
		}
		
		private Convocatorium convocatorium;
		public virtual Convocatorium Convocatorium
		{
			get
			{
				return this.convocatorium;
			}
			set
			{
				this.convocatorium = value;
			}
		}
		
		private IList<EtapaCofecyt> etapaCofecyts = new List<EtapaCofecyt>();
		public virtual IList<EtapaCofecyt> EtapaCofecyts
		{
			get
			{
				return this.etapaCofecyts;
			}
		}
		
		private IList<ActividadCofecyt> actividadCofecyts = new List<ActividadCofecyt>();
		public virtual IList<ActividadCofecyt> ActividadCofecyts
		{
			get
			{
				return this.actividadCofecyts;
			}
		}
		
	}
}
#pragma warning restore 1591
