#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using CapaDominio;

namespace CapaDominio	
{
	public partial class TipoEstadoEtapa
	{
		private int idTipoEstadoEtapa;
		public virtual int IdTipoEstadoEtapa
		{
			get
			{
				return this.idTipoEstadoEtapa;
			}
			set
			{
				this.idTipoEstadoEtapa = value;
			}
		}
		
		private string nombre;
		public virtual string Nombre
		{
			get
			{
				return this.nombre;
			}
			set
			{
				this.nombre = value;
			}
		}
		
		private IList<Etapa> etapas = new List<Etapa>();
		public virtual IList<Etapa> Etapas
		{
			get
			{
				return this.etapas;
			}
		}
		
		private IList<EtapaCofecyt> etapaCofecyts = new List<EtapaCofecyt>();
		public virtual IList<EtapaCofecyt> EtapaCofecyts
		{
			get
			{
				return this.etapaCofecyts;
			}
		}
		
	}
}
#pragma warning restore 1591
