#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace CapaDominio	
{
	public partial class Usuario
	{
		private int idUsuario;
		public virtual int IdUsuario
		{
			get
			{
				return this.idUsuario;
			}
			set
			{
				this.idUsuario = value;
			}
		}
		
		private string nombre;
		public virtual string Nombre
		{
			get
			{
				return this.nombre;
			}
			set
			{
				this.nombre = value;
			}
		}
		
		private string mail;
		public virtual string Mail
		{
			get
			{
				return this.mail;
			}
			set
			{
				this.mail = value;
			}
		}
		
		private string contrasenia;
		public virtual string Contrasenia
		{
			get
			{
				return this.contrasenia;
			}
			set
			{
				this.contrasenia = value;
			}
		}
		
		private int? grupo;
		public virtual int? Grupo
		{
			get
			{
				return this.grupo;
			}
			set
			{
				this.grupo = value;
			}
		}
		
	}
}
#pragma warning restore 1591
